layer2tech/mercury-wallet

src/components/CopiedButton/copiedButton.css
src/components/CopiedButton/index.js
src/components/displaySeed/displaySeed.js
src/components/index.js
src/components/transactionsBTC/transactionsBTC.js
src/containers/BackupTx/BackupTx.js
src/containers/Receive/Receive.js
src/containers/Send/Send.js

- https://github.com/commerceblock/mercury-wallet/issues/193
I had added a new component called CopiedButton which will show the text 'Copied!' if user click copy button, and it will hide after 1s. I had update some pages have the copy button such as: transactionsBTC, BackupTx, Receive, Send.

Issue#193: Feedback on copying address

---

src/settings.json
src/store.ts

Correct password field deletion error in storage to enable unit test pass for wallet save/load - password field set to empty string instead of being deleted.

Wallet ser test

---

src/containers/Receive/Receive.js
src/features/WalletDataSlice.js
src/settings.json
src/wallet/http_client.ts
src/wallet/statecoin.ts
src/wallet/wallet.ts

Statecoin transfers can be received without the transfer message - by leaving the message box empty, the wallet queries the server by proof key (SE address) to fetch the transfer messages, and then completes them. 
Will update the UI in a separate PR.

Get transfers

---

src/containers/Withdraw/Withdraw.js
src/features/WalletDataSlice.js
src/wallet/wallet.ts

Deposit_confirm is now completed as soon as the deposit tx is found in the mempool. This means that the owner always has the backup tx (protects against the server disappearing between deposit tx sending and 3 confs - could be days potentially). 
The statecoin status in the wallet is not updated (and remains unspendable/swappable) until the required confirmations are received.

Deposit confirm on tx

---

src/components/coins/coins.js
src/containers/Swap/Swap.js

Enables returning to spendable coins list if in_transfer or withdrawn are empty.

filter options in empty lists

---

src/components/displaySeed/displaySeed.js

Fix: Issue #456 the ability to copy seed to clipboard has been commented out. This allows it to be used for development reasons location displaySeed.js : <Copied Button/>

Fix: Issue #456 Comment Out Copy Seed to Clipboard

---

src/components/coins/coins.css
src/components/coins/coins.js

Issue #474 Fixed:
- Unconfirmed Coins appear unavailable in Swaps with hue over them
- Error message appears, "Coins unavailable for swap - awaiting confirmations"

Fix: Issue #474 Unconfirmed Coins Selectable in Swaps

---

src/features/ThemeSlice.js

A bug occurred in the ui where if this variable is left in there, the toggle switch disappears.

hotfix/ ensure wallet doesn't load the dark_mode variable

---

src/containers/Withdraw/Withdraw.js
src/electron-starter.js
src/wallet/mercury/withdraw.ts
src/wallet/util.ts

Fix Issue #595 
• Merge with server restart to ensure coins don't break
• Backup transaction fee changed to 141
• Virtual bytes used to set fee
• Maximum fee set assuming P2PKH transactions

FIX: Issue #595 Withdrawal Miner Fee

---

src/components/coins/FilterBy/FilterBy.css
src/components/coins/FilterBy/FilterBy.js
src/components/coins/SortBy/SortBy.css
src/components/coins/coins.js

FIX: Issue #619 
• Withdrawn and transferred coins no longer appear on Send, Withdraw and Swap pages
• Instead of coins being greyed out and made unavailable they have been removed entirely

FIX: issue#619 withdrawn and transferred coins unavailable on function pages

---

src/containers/Withdraw/Withdraw.js

Issue #660  Issue #691 
Withdraw Modal now exits smoothly if there is an error

Fix: Withdraw modal exits smoothly

---

src/components/ConfirmPopup/index.js
src/containers/Receive/Receive.css
src/containers/Swap/Swap.js
src/features/WalletDataSlice.js
src/wallet/wallet.ts

Fix: Issue #783 
• Swap warning only given during swap : coins remove from "swapRecords" in case of swap completion or swap failure
• Styling fix on Receive buttons with index > 100
• Warning dialogue fix

FIX: Issue #783 Logout Swap Warning

---

tor-adapter/server/index.js

This fixes the problem that is preventing the swap conductor connection status being displayed correctly.

Correct the swap conductor ping API in the tor adapter.

---

src/wallet/wallet.ts

On deposit confirm, check that the the current blockheight is reasonable (not zero, which can result from a failed getblockheight call earlier). If not, try to fetch it again, then throw error.

blockheight check and fetch on deposit

---

package.json
public/electron.js
src/containers/App/App.js
src/electron-starter.js
src/wallet/recovery.ts
tor-adapter/package.json
tor-adapter/server/index.js
tor-adapter/server/tor_client.js

- Cleanly terminate the tor-adapter and tor node processes on shutdown (the tor adapter now shuts down the tor node on SIGINT or SIGTERM signals by sending SIGTERM to the tor node and, if that fails, SIGKILL).
- Terminate the tor adapter process on startup, if running (on windows, kill the parent mercurywallet.exe process)

Kill existing tor adapter

---

src/wallet/mercury/deposit.ts
src/wallet/statecoin.ts
src/wallet/wallet.ts

Keep the same locktime for subsequent deposit backup txs in case of replacement. 
This will also be enforced by the server.

keep locktime for replacement txs

---

src/components/createStatecoin/createStatecoin.js

Issue #1002 :
• Coins below 0.001BTC not shown on deposit display coin suggestion
• Unrounded strange accidental coin deposits not shown if liquidity less than 3

Issue #1002 Deposit Coin value Display

---

src/wallet/mercury/transfer.ts

The batch ID is added to transfer message 1 in transfer_sender. If a non-batch transfer, it is set to null.

Batch id for transfer sender

---

src/components/coins/coins.js

Issue #1091 Fixed:
Expiry date is calculated by : blocks until expiry - current block height
If connection drops block height is set to null:
blocks until expiry - null = blocks until expiry, which is a lot higher than it's meant to be
This is now shown as an error state which displays expiry date as "--"

Expiry date not set when connection drops

---

src/containers/Swap/Swap.js

- Update swap group info every 6 seconds
- Update swap group info on clicking join/leave
- Do not call dispatch(callUpdateSwapStatus()) in this loop; this is only required on wallet startup

Optimise update of swap group info.

---

src/wallet/test/wallet.test.js

Update config test: config logs invalid values as a warning

Update config test

---

src/components/coins/Coin/Coin.js
src/components/coins/coins.css

Issue #1439: Duplicate tooltip hovers over entire coin panel - easier to see.

Issue #1439 Duplicate Coin Tooltip

---

src/containers/Send/Send.js
src/store.ts
src/wallet/test/wallet.test.js

Issue #1633
• Old wallet files don't have "swapped_ids" properties in store
- Loading this property returns undefined
- undefined values have no property .slice

HOTFIX: Issue #1633 - Err in Wallet Load

---

src/wallet/types.ts

Allow s2_pub in TransferFinalizeData to be null after transfer_receiver failure retry.

fix typeforce on finalize data

---

src/features/WalletDataSlice.js

There is no need for this before the wallet is created - it is set as soon as the wallet connects.

Remove block height call on init
