layer2tech/mercury-wallet

- src/wallet/config.ts
- src/wallet/electrum.ts
- src/wallet/http_client.ts
- src/wallet/index.js
- src/wallet/test/mercury.test.js
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
> Config struct in Wallet

- src/wallet/mercury/deposit.ts
- src/wallet/mercury/ecdsa.ts
Statchain IDs and User IDs are now received from the server as objects.
> ID API change for ecdsa and deposit

- src/wallet/activity_log.ts
- src/wallet/statecoin.ts
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
- Create new wallet cleaned up
- Confirm user saved mnemonic fn
- Save wallet cleanup: Store as JSON using Electron-store 
- Save individual data example with update StateCoinList 
- Load wallet from Store
> Startup fns

- src/wallet/http_client.ts
- src/wallet/mercury/transfer.ts
- src/wallet/types.ts
- src/wallet/util.ts
Get SE pubkey in transfer_receiver (transfer/pubkey) and then encrypt the t2 value.
> encryption of t2

- src/containers/Home/Home.js
- src/containers/LoadWallet/LoadWallet.js
- src/features/WalletDataSlice.js
- src/store.ts
- src/wallet/http_client.ts
- src/wallet/index.js
- src/wallet/mercury/deposit.ts
- src/wallet/test/util.test.js
- src/wallet/test/wallet.test.js
- src/wallet/util.ts
- src/wallet/wallet.ts
- Multiple wallet support
- Password encrypts mnemonic
- removed xpriv's from storage
> Multiple wallets

- src/components/panelControl/panelControl.css
- src/containers/CreateWalletInfo/CreateWalletInfo.css
- src/containers/Deposit/Deposit.css
- src/containers/LoadWallet/LoadWallet.css
- src/containers/LoadWallet/LoadWallet.js
- src/containers/RestoreWallet/RestoreWallet.css
- src/containers/RestoreWallet/RestoreWallet.js
Show text on buttons on tablet screen
> Style fixes

- src/components/confirmSeed/confirmSeed.js
- src/containers/App/App.js
- src/containers/BackupTx/BackupTx.js
- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/Deposit/Deposit.js
- src/containers/Home/Home.js
- src/containers/LoadWallet/LoadWallet.js
- src/containers/Receive/Receive.js
- src/containers/Send/Send.js
- src/containers/Settings/Settings.js
- src/containers/Withdraw/Withdraw.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
- Improve wallet load/creation process
- allow logouts 
- catch wallet reload error when in developer mode
- some formatting
> Wallet loading

- src/containers/Deposit/Deposit.js
RE: https://github.com/commerceblock/mercury-wallet/issues/24
> rm default value selection

- src/containers/Deposit/Deposit.js
- src/containers/Receive/Receive.js
- src/wallet/wallet.ts
https://github.com/commerceblock/mercury-wallet/issues/37
> Transfer rec msg

- src/containers/LoadWallet/LoadWallet.js
Wallet list refresh required restart. Fixed.
> refresh list of loaded wallet without restart

- README.md
- src/components/confirmSeed/confirmSeed.js
- src/features/WalletDataSlice.js
- src/wallet/electrum.ts
- src/wallet/mocks/mock_electrum.ts
- src/wallet/statecoin.ts
- src/wallet/test/mercury.test.js
- src/wallet/types.ts
- src/wallet/wallet.ts
Setting testing_mode removes some inconveniences to make testing easier and faster:
- No seed confirmation
- Electrum calls mocked so no need to send and wait for funding transactions
> Add testing mode

- main.js
- src/containers/BackupTx/BackupTx.js
- src/electron-starter.js
- src/features/WalletDataSlice.js
- src/wallet/config.ts
- src/wallet/index.js
- src/wallet/mercury/deposit.ts
- src/wallet/statecoin.ts
- src/wallet/test/util.test.js
- src/wallet/test/wallet.test.js
- src/wallet/util.ts
- src/wallet/wallet.ts
Wallet watches block height and broadcasts backup transaction at nlocktime.
Backup transaction status displayed: 'pre-locktime', 'in mempool', 'confirmed', 'taken', 'spent'.
CPFP create option and status indication.
CPFP transaction broadcast automatically with backup transaction.
> Backup tx features

- src/components/ConfirmPopup/index.js
- src/components/ErrorPopup/index.css
- src/components/ErrorPopup/index.js
- src/components/NotificationBar/index.js
- src/components/header/header.js
- src/components/index.js
move all logic from header to independent component. Same as error popup modal
> Issue#131, 132: update notification, error message

- src/containers/CreateWalletInfo/CreateWalletInfo.css
- src/containers/CreateWalletInfo/CreateWalletInfo.js
- src/containers/Help/Help.css
- https://github.com/commerceblock/mercury-wallet/issues/140
- https://github.com/commerceblock/mercury-wallet/issues/142
> Issue#140, 142

- src/components/transactionsBTC/transactionsBTC.js
- src/containers/Deposit/Deposit.css
- https://github.com/commerceblock/mercury-wallet/issues/191
> Issue#191: remove initialised coin CSS

- src/components/createStatecoin/createStatecoin.js
- src/components/createStatecoin/valueSelection/valueSelection.js
- https://github.com/commerceblock/mercury-wallet/issues/192
> Issue#192: Deposit page sorting bug

- src/components/createStatecoin/createStatecoin.js
- src/components/panelConnectivity/panelConnectivity.js
- src/components/swaps/swaps.js
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/wallet/util.ts
- src/wallet/wallet.ts
- React-ify swap group data updates
- update coins list in GUI throughout swap process
> Swaps page clean

- src/components/Steppers/index.js
- src/components/createStatecoin/createStatecoin.js
- src/components/createStatecoin/valueSelection/valueSelection.js
- src/components/panelConnectivity/panelConnectivity.js
- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/Deposit/Deposit.css
- src/containers/Deposit/Deposit.js
- src/features/WalletDataSlice.js
- src/wallet/http_client.ts
- src/wallet/mercury/info_api.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- conductor connectivity marker
- display swap groups information
- fix fee display
> Conductor connect info

- src/containers/BackupTx/BackupTx.css
- https://github.com/commerceblock/mercury-wallet/issues/197
> Issue#197: TransferMessage out of range

- src/components/ErrorPopup/index.js
- https://github.com/commerceblock/mercury-wallet/issues/211
> Issue#211: Built wallet error message CSS

- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/wallet/http_client.ts
- src/wallet/swap/info_api.ts
- src/wallet/swap/swap.ts
Must be merged alongside https://github.com/commerceblock/mercury/pull/169
> call deregister-utxo API when removing coin from swap pool

- src/containers/Settings/Settings.js
- src/store.ts
- Remove Logout button from `Settings` page
- Show Clear Wallet button only in testing_mode
- Remove testing_mode settings from storage
> Settings buttons

- src/components/createWizardForm/createWizardForm.js
- src/containers/RestoreWallet/RestoreWallet.css
- src/containers/RestoreWallet/RestoreWallet.js
- https://github.com/commerceblock/mercury-wallet/issues/229
> Issue#229: Password input in restore wallet page same as password input in createwallet page

- src/wallet/statecoin.ts
- src/wallet/swap/swap.ts
I couldnt repeat [this](https://github.com/commerceblock/mercury-wallet/issues/162) bug, however changes have been made to coin display in the `Coins` panel since the bug was created so it may have fixed itself. 
Changes in this PR are instead for efficieny and error prevention
> prevent unnecessary code repeating

- src/containers/Send/Send.js
- src/containers/Swap/Swap.js
- src/containers/Withdraw/Withdraw.js
https://github.com/commerceblock/mercury-wallet/issues/215
> auto refresh coins list upon send and withdraw

- src/components/coins/FilterBy/FilterBy.css
- src/components/coins/FilterBy/FilterBy.js
- src/components/coins/SortBy/SortBy.css
- src/components/coins/coins.css
- src/components/coins/coins.js
- src/components/panelControl/panelControl.css
- src/components/panelControl/panelControl.js
- src/containers/Withdraw/Withdraw.js
- https://github.com/layer2tech/mercury-wallet/issues/245
> MW-245: Move Coins filtering to Coins panel so that it can be used in Withdraw, Send and Backup tx page

- src/containers/BackupTx/BackupTx.js
- src/features/WalletDataSlice.js
- src/wallet/statecoin.ts
- src/wallet/test/wallet.test.js
BackupTx page was not able to perform Transaction.toHex() on JSON Object. To fix I have rebuilt back up txs as Transactions at load time.
Also changed `callCreateBackupTxCPFP` to be a thunk so that errors thrown inside it will be shown to the user.
https://github.com/commerceblock/mercury-wallet/issues/230
> Backup tx data load

- public/electron.js
- src/electron-starter.js
- https://github.com/layer2tech/mercury-wallet/issues/143
> Menu removal

- public/electron.js
- src/electron-starter.js
- https://github.com/layer2tech/mercury-wallet/issues/143
> only hide menu for linux system

- src/components/createStatecoin/createStatecoin.js
- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/LoadWallet/LoadWallet.js
- src/containers/RestoreWallet/RestoreWallet.js
- src/store.ts
https://github.com/layer2tech/mercury-wallet/issues/260
> Check wallet name not already taken

- src/containers/LoadWallet/LoadWallet.js
- src/containers/Withdraw/Withdraw.js
- src/features/WalletDataSlice.js
- src/store.ts
- src/wallet/config.ts
- src/wallet/electrum.ts
- src/wallet/mercury/withdraw.ts
- src/wallet/mocks/mock_electrum.ts
- src/wallet/test/mercury.test.js
- src/wallet/test/util.test.js
- src/wallet/test/wallet.test.js
- src/wallet/util.ts
- src/wallet/wallet.ts
Started PR again due to merge issues
> Estimate fee

- package.json
- src/components/transactionsBTC/transactionsBTC.js
- src/containers/Deposit/Deposit.css
- src/features/WalletDataSlice.js
- https://github.com/layer2tech/mercury-wallet/issues/279
> Progress indicators

- src/components/CopiedButton/copiedButton.css
- src/containers/BackupTx/BackupTx.css
- src/containers/BackupTx/BackupTx.js
- https://github.com/layer2tech/mercury-wallet/issues/121
> Backup page enhancement

- src/components/ErrorPopup/index.css
- src/containers/Receive/Receive.css
- src/containers/Receive/Receive.js
> Receive coin statecoins UX

- src/components/coins/coins.css
- src/components/coins/coins.js
- src/containers/Swap/Swap.js
- https://github.com/layer2tech/mercury-wallet/issues/291
- https://github.com/layer2tech/mercury-wallet/issues/293
> show notify for swaplimit & single select only

- src/components/SendModal/index.js
- src/containers/Send/Send.js
- https://github.com/layer2tech/mercury-wallet/issues/298
> Transfer modal

- src/components/coins/coins.css
- src/components/coins/coins.js
- https://github.com/layer2tech/mercury-wallet/issues/299
> Coin display Layout

- src/components/CoinStatus/index.js
- src/components/coins/coins.js
- src/components/panelControl/panelControl.js
- src/wallet/statecoin.ts
Sent coins not included in balance or coin count. 
Not included by default in the coins list.
> transferred coins unavailable

- public/electron.js
- src/electron-starter.js
* Change the way the linux application menu is removed from the browser window to enable the app to start up in linux.
> Linux menu

- src/components/coins/coins.css
- src/components/coins/coins.js
- https://github.com/layer2tech/mercury-wallet/issues/305
> show no coin message

- package.json
- public/electron.js
- src/electron-starter.js
* Enable hardened runtime
* Remove 'alert' on tor-adapter start error
> Startup correct

- src/components/BackupWalletPopup/index.css
- src/components/BackupWalletPopup/index.js
- src/components/ConfirmPopup/index.css
- src/components/ConfirmPopup/index.js
- src/components/ErrorPopup/index.js
- src/components/confirmSeed/confirmSeed.js
- src/components/createWizardForm/createWizardForm.js
- src/components/displaySeed/displaySeed.js
- src/components/index.css
- src/containers/CreateWalletInfo/CreateWalletInfo.css
- src/containers/CreateWalletInfo/CreateWalletInfo.js
- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/Deposit/Deposit.css
- src/containers/Deposit/Deposit.js
- src/containers/LoadWallet/LoadWallet.css
- src/containers/LoadWallet/LoadWallet.js
- src/containers/RestoreWallet/RestoreWallet.css
- src/containers/RestoreWallet/RestoreWallet.js
- src/containers/Settings/Settings.css
- src/containers/Settings/Settings.js
- src/containers/Welcome/Welcome.css
- src/containers/Welcome/Welcome.js
- https://github.com/layer2tech/mercury-wallet/issues/325
> Button shape

- src/components/Tutorial/tutorial.css
- src/containers/Swap/Swap.css
- src/containers/Swap/Swap.js
- https://github.com/layer2tech/mercury-wallet/issues/324
> Swaps page design layout

- src/containers/BackupTx/BackupTx.js
- src/containers/Deposit/Deposit.css
- src/containers/Deposit/Deposit.js
- src/containers/Settings/Settings.js
- https://github.com/layer2tech/mercury-wallet/issues/333
> Tutorial boxes

- src/components/coins/FilterBy/FilterBy.css
- src/components/coins/SortBy/SortBy.css
- src/components/coins/SortBy/SortBy.js
- src/components/panelControl/panelControl.css
- src/containers/App/AppDarkMode.css
- https://github.com/layer2tech/mercury-wallet/issues/336
> Coinslist sort and filter buttons

- src/components/coins/coins.js
- src/components/panelCoinsActivity/panelCoinsActivity.js
- https://github.com/layer2tech/mercury-wallet/issues/335
> Narrow coins list initialization

- src/components/Tutorial/tutorial.css
- src/components/coins/coins.css
- src/components/coins/coins.js
- src/components/index.css
- src/components/panelCoinsActivity/panelCoinsActivity.css
- src/containers/App/AppDarkMode.css
- src/containers/CreateWalletInfo/CreateWalletInfo.css
- src/containers/Swap/Swap.css
- src/containers/Welcome/Welcome.css
- https://github.com/layer2tech/mercury-wallet/issues/334
> Box rounding and shadows

- README.md
- package.json
- public/electron.js
- resources/etc/torrc
- src/containers/Home/Home.js
- src/containers/RestoreWallet/RestoreWallet.js
- src/electron-starter.js
- src/settings.json
- src/wallet/config.ts
- src/wallet/test/tor.test.js
- src/wallet/wallet.ts
- tor-adapter/package-lock.json
- tor-adapter/package.json
- tor-adapter/server/config.js
- tor-adapter/server/index.js
- tor-adapter/server/settings.json
- tor-adapter/server/tor_client.js
* Automatic tor process startup/shutdown - no user configuration required
> Bin distro

- src/components/coins/coins.css
- src/components/createStatecoin/valueSelection/valueSelection.js
- src/containers/Deposit/Deposit.css
- https://github.com/layer2tech/mercury-wallet/issues/338
> Deposit amounts box and liquidity bars

- src/components/confirmSeed/confirmSeed.js
- https://github.com/layer2tech/mercury-wallet/issues/352
> Seed words layout

- src/containers/LoadWallet/LoadWallet.js
Checks if item from wallet list is object or string (which may be OS dependent).
> Load string

- src/components/transactionsBTC/transactionsBTC.js
- src/containers/App/AppDarkMode.css
- https://github.com/layer2tech/mercury-wallet/issues/344
> Obscure deposit address after funding tx receipt

- src/components/swaps/swaps.js
- https://github.com/layer2tech/mercury-wallet/issues/354
> Swap group status labels

- public/electron.js
- src/electron-starter.js
- tor-adapter/package-lock.json
- tor-adapter/package.json
- tor-adapter/server/index.js
- tor-adapter/server/tor_client.js
* Use node-tor-control package instead of using netcat for tor control
> Debug win tc

- src/components/panelConnectivity/panelConnectivity.js
> Fix/283: Update component if blockheight changes

- src/wallet/mercury/info_api.ts
> Fix/275: typeforce exception smt

- src/wallet/mercury/info_api.ts
Reverts layer2tech/mercury-wallet#390
> Revert "Fix/275: typeforce exception smt"

- src/components/activity/activity.js
> Fix warning with keys

- src/components/createStatecoin/valueSelection/valueSelection.js
> Statecoin highlighted but not selected

- src/containers/BackupTx/BackupTx.js
- src/wallet/wallet.ts
Single deposit_confirm call on tx receipt. 
Deposit confirm for confirmed txs on start
CPFP bug fix. 
Wallet save on CPFP update.
> deposit process and cpfp fix

- src/containers/Receive/Receive.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
Added 'Next' and 'Prev' buttons to select and view generated wallet addresses. 
Retrieve transfer message from selected address only. 
Fixed bug with latest address not being saved.
> Receive addresses

- src/components/coins/coins.css
https://github.com/layer2tech/mercury-wallet/issues/387
> Coinslist mouse-over highlighting

- package.json
- src/components/createStatecoin/valueSelection/valueSelection.js
- src/containers/Deposit/Deposit.css
- https://github.com/layer2tech/mercury-wallet/issues/388
> Deposit custom amount

- src/components/CoinStatus/index.js
- src/settings.json
- src/wallet/statecoin.ts
> Wallet modal return confirmations

- src/components/panelConnectivity/panelConnectivity.js
> Divide total pooled by 10^8

- src/wallet/wallet.ts
Test mode (with mock electrum server) deposit confirm on button.
> Test mode fix

- src/components/coins/FilterBy/FilterBy.css
- src/components/coins/coins.css
- src/components/coins/coins.js
- src/components/panelCoinsActivity/panelCoinsActivity.css
- src/components/panelCoinsActivity/panelCoinsActivity.js
Added the filter button into the empty coinslist
Made styling of withdraw tab more in style with other nav-tabs
> fix: Issue #423 filter button added on empty coinslist

- src/wallet/electrum.ts
Improves error reporting
https://github.com/layer2tech/mercury-wallet/issues/421
> Define and use a ElectrumClientError class

- src/features/WalletDataSlice.js
- src/wallet/electrum.ts
Attempt to reconnect before electrum api calls if necessary
> Electrum reconnect

- src/components/CoinStatus/coinStatus.css
- src/components/coins/coins.css
- src/components/coins/coins.js
- src/containers/App/App.css
Issue #409 Resizing wallet solved
- Withdraw, Swap and Home page fixed for sizes in range width: 500px-900px
- App min width set at 500px
> Fix: Resizing Wallet

- public/index.html
- src/components/coins/coins.js
Fix: Issue #446 icon directory replace default icon in shortcut icon space index.html
> Fix: icon changed in index file

- src/components/activity/activity.js
- src/components/coins/EmptyCoinDisplay/EmptyCoinDisplay.js
- src/components/coins/coins.js
- Issue #463 Fixed
-  Display "No coins transferred" and "No coins withdrawn" for better UI
> Fix: Issue #463 UI display when no coin data for withdrawn/transfer

- src/containers/Help/Help.js
> Fix: Issue #462 social tab

- src/wallet/wallet.ts
Issue #485 Fixed:
- Swaplimit coins now available for withdrawal
> Fix :Issue#485 Swaplimit Coins Available for Withdraw

- src/containers/Deposit/Deposit.css
Issue #460 Fixed:
• The blue tick SVG removed on deposit screen
• Blue border added on click
> Fix: Issue #460 resize wallet deposit screen

- src/components/coins/FilterBy/FilterBy.css
- src/components/coins/SortBy/SortBy.css
- src/components/coins/coins.css
- src/components/coins/coins.js
- src/components/panelControl/panelControl.css
Issue #470  Fixed
• Coinslist lowered so top coin and filter button don't overlap
• Z-index of filter button increase
• No longer shows over error messages
> Fix/470 Can't. Select Coinslist Filter

- src/components/coins/FilterBy/FilterBy.css
• Filter button added above menu overlay
> Fix: Filter button above menu overlay

- src/components/TermsConditions/TermsConditions.js
- src/components/createWizardForm/createWizardForm.css
- src/components/createWizardForm/createWizardForm.js
- src/containers/Help/Help.js
Fix: Issue #503 
• Link added to agree T&Cs term
• T&Cs appear over screen
• Styling changes for this on restoreWallet page
> Fix: Issue #503 add link to agree tcs

- package.json
• Fix: Refresh 'Receive' Page
• Fix: QR code UI error caused by git conflict resolution
• Update the swap test to account for changes to swap phase 1
> Version v0.3.4

- src/components/CoinStatus/coinStatus.css
- src/components/coins/coins.css
- src/containers/App/App.css
• Revert unreverted in this fix
> Fix: Resizing Coinslist unrevert fix

- src/containers/Receive/Receive.css
- src/containers/Receive/Receive.js
- src/containers/Send/Send.js
- src/containers/Welcome/Welcome.js
- src/features/WalletDataSlice.js
Fix: Issue #518 
• Restyling of receive page
• Dialogue box to enter transfer key available on click 'Receive with Key'
> Fix/518 receive statecoin UI changes

- src/components/createStatecoin/createStatecoin.js
- src/components/createStatecoin/valueSelection/valueSelection.js
- src/wallet/util.ts
> Fix/#469, #510

- src/components/swaps/swaps.css
FIX: Issue #560 
• Highlighting on hover removed
• Cursor changed from pointer to default
> Fix: Issue #560 Remove Swap Group Highlighting

- src/components/coins/coins.css
- src/components/coins/coins.js
> Fix/475 - Deposit below threshold error state

- src/components/CoinStatus/index.js
- src/components/coins/SwapStatus/SwapStatus.js
- src/components/coins/coins.css
- src/components/coins/coins.js
Added Swaps Progress indication
4 different phases appear below coin status during a swap
> Feat: Issue#467 Swaps Progress Indication

- src/components/coins/coins.js
#422 fixes coins being reset and a bug with months/days in the modal box
> Fix/422 - Coins disappear on load from memory

- src/components/CoinStatus/coinStatus.css
- src/components/coins/coins.css
- src/components/coins/coins.js
- src/containers/Receive/Receive.js
- src/containers/Send/Send.js
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
Fix Issue #585
Fix Issue #561 
• All coin statuses now appear on send page
> Fix/585 coin statuses on send page & Issue #561 Disable Receive calls and Swaps when Electrum server down

- src/components/coins/coins.css
- src/components/coins/coins.js
- src/containers/Withdraw/Withdraw.js
Fix Issue #586 
• Coins IN_SWAP and AWAITING_SWAP unavailable for sending and withdrawing
> FIX: Issue#586 Swap Coins unavailable for send and withdrawal

- src/components/SendModal/index.css
- src/components/SendModal/index.js
- src/containers/Send/Send.js
Issue #517:
• Tooltip added to Transfer Key
> Fix: Issue #517 tooltip to transfer key send modal

- src/containers/Receive/Receive.css
- src/containers/Receive/Receive.js
FEATURE ADDED #609:
• Buttons inactive while receiving coins data from server
• Loading... animation appears in buttons
> FEAT: issue#609 Receive Coins loading... buffer

- src/containers/Deposit/Deposit.css
> FIX: Deposit Init Styling

- src/components/swaps/swaps.js
- src/containers/Withdraw/Withdraw.css
- src/containers/Withdraw/Withdraw.js
- src/wallet/recovery.ts
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
Issue #618 : Withdrawal TX hex added to coin modal
Issue #617: Withdrawal progress indicator, withdraw hash added to coin modal, withdraw modal displaying txid
Issue #608:  Swap progress indicator as on Withdraw page
Issue #631: Coins below swap limit available for send
> FEAT: Issues resolved: 618,617,608,631

- src/components/coins/coins.js
- src/containers/Send/Send.js
• Fix: Issue #638 
• Coins list updates after coin sent
> FIX: Issue #638 Send Page Coinslist Update

- src/components/createStatecoin/createStatecoin.js
> fix/620  - coin info

- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/LoadWallet/LoadWallet.css
- src/containers/LoadWallet/LoadWallet.js
- src/containers/RestoreWallet/RestoreWallet.js
- src/features/WalletDataSlice.js
- src/store.ts
- src/wallet/wallet.ts
NEW FEATURE ADDED: Issue #555  Delete wallet feature
• File structure for saving wallets changed
• Each wallet has separate directory
> Issue #555 New Delete Feature Added

- src/components/coins/coins.js
> fix/673  - add tooltip for  batch withdraw error coins

- src/components/coins/coins.css
- src/components/coins/coins.js
- src/components/transactionsBTC/transactionsBTC.js
- src/containers/Deposit/Deposit.js
- src/containers/Withdraw/Withdraw.js
- src/features/WalletDataSlice.js
- src/wallet/statecoin.ts
- src/wallet/wallet.ts
• Tx Hex on withdrawal coin modal fixed
• Withdraw Modal closes when clicking away from it
• SC addresses depositing error fixed
> Fixes: Tx_Hex formatting, Withdraw Modal and SC addresses

- src/containers/Deposit/Deposit.js
- src/containers/Receive/Receive.css
- src/containers/Receive/Receive.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
Issue #687 Receive UI + unrelated swap SC address fix
• Tooltip added to show which addresses are available
• Swap Sc addresses functions normally
> Fix/687 swap scaddresses receive UI tooltip

- src/components/coins/coins.js
- src/settings.json
- src/wallet/mercury/deposit.ts
- src/wallet/wallet.ts
Fixed bug where coin status could change to withdrawn with error in electrum server connection.
> Fix backupstatus

- src/components/panelConnectivity/panelConnectivity.js
- src/containers/Withdraw/Withdraw.js
> fix/ withdrawal  bug  & block height

- src/containers/Receive/Receive.css
> fix arrow borders

- src/components/swaps/CountdownTimer/CountdownTimer.css
- src/components/swaps/CountdownTimer/CountdownTimer.js
- src/components/swaps/swaps.css
- src/components/swaps/swaps.js
- src/containers/Swap/Swap.js
FEATURE ADDED!!
New countdown clock.
• Colour ring around clock changes depending on time remaining 
• SWAP LIVE message when countdown reaches 0
> FEAT: New Countdown Clock on Swap Page

- src/components/coins/coins.css
- src/components/coins/coins.js
New Feature Added!
• Tooltip explaining each swap phase
> FEAT: Tooltip for Swap Phases

- src/components/panelConnectivity/panelConnectivity.js
- src/containers/Swap/Swap.css
• Loading button doesn't change size on click 'JOIN GROUP'
• Bitcoin Network Host URL truncated and is fully available on hover
> CHORE: Loading font-size and truncate BTC

- src/components/coins/coins.js
- src/components/swaps/CountdownTimer/CountdownTimer.js
• Swap clock doesn't show live when not live
• Status hover fix
> Quick Fixes for countdown timer and status hover

- src/components/ConfirmPopup/index.js
- src/components/WarningPopup/index.css
- src/components/WarningPopup/index.js
- src/components/header/header.js
- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/Settings/Settings.js
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
• Coin punishment explained on adding a coin to a swap
> Punshiment Warning

- src/components/inputs/CoinDescription/CoinDescription.js
- src/containers/CreateWalletWizard/CreateWalletWizard.js
- src/containers/Withdraw/Withdraw.css
- src/containers/Withdraw/Withdraw.js
- src/features/WalletDataSlice.js
- src/wallet/electrs.ts
- src/wallet/electrum.ts
- src/wallet/mercury/withdraw.ts
- src/wallet/mocks/mock_electrum.ts
- src/wallet/test/mercury.test.js
- src/wallet/test/util.test.js
- src/wallet/test/wallet.test.js
- src/wallet/util.ts
- src/wallet/wallet.ts
Issue #751 Withdrawal Fee Estimation
• https://blockstream.info/ now used for fee estimations
Issue #744 FIX
• Wallet directories no longer created by typing
> Feat: Withdrawal Fee Estimation more accurate

- src/network.json
- tor-adapter/server/settings.json
Electrum server to onion address.
Swap server as separate onion address (on separate tor relay node).
> updated onion endpoints

- src/components/swaps/CountdownTimer/CountdownTimer.js
• Countdown styling proportional to an hour
> MERGE WHEN SERVER SWAP FREQUENCY CHANGED TO AN HOUR

- src/components/CoinStatus/index.js
- src/components/confirmSeed/confirmSeed.js
- src/containers/LoadWallet/LoadWallet.js
- src/containers/Receive/Receive.js
- src/containers/Send/Send.js
- src/features/WalletDataSlice.js
- src/wallet/recovery.ts
- src/wallet/util.ts
- src/wallet/wallet.ts
Address index reset on exit wallet
Recovery fecthes sc address index 0
Amount and address in loading transfer_sender
Deposit BTC on awaiting transaction
> fixes to sc addresses and recovery

- src/wallet/http_client.ts
- src/wallet/mercury/info_api.ts
- src/wallet/mercury/transfer.ts
vout any length in get_statechain deserialization. 
Can complete receive of coin that has already done transfer and statechain update.
> receive recover and vout length

- src/components/panelConnectivity/panelConnectivity.js
- src/wallet/mercury/ecdsa.ts
- src/wallet/mercury/transfer.ts
- src/wallet/swap/swap.ts
- tor-adapter/server/index.js
Reverts layer2tech/mercury-wallet#847
> Revert "Swap retries"

- src/containers/App/AppDarkMode.css
Issue #814 : Dark Mode Tooltip Receive Page
> Issue #814 Dark Mode Tooltip Receive

- src/components/activity/activity.css
Issue #813: Full TxID can be viewed on hover in activity log
> CHORE: #813 Txid Hover Activity Log

- public/electron.js
- tor-adapter/server/index.js
Fixes issue #860 Adaptor shutting down when machine sleeps?
> Do not shutdown tor adaptor based on timeout.

- public/index.html
- src/containers/App/App.js
- src/features/WalletDataSlice.js
Issue #877 : Wallet Name added to window title
> FEAT: Issue #877 Display Loaded Wallet Name

- src/components/transactionsBTC/transactionsBTC.js
Issue #878 : X Unclickable once transaction received on deposit page
> Issue #878: X Unclickable on Transaction Received

- src/components/CoinStatus/coinStatus.css
> Issue #862 Resizing Transferred Coin Status

- src/components/activity/activity.css
- src/components/activity/activity.js
- src/components/coins/coins.js
- src/components/createStatecoin/valueSelection/valueSelection.js
- src/components/index.css
- src/containers/App/App.js
- src/containers/BackupTx/BackupTx.css
- src/containers/Receive/Receive.js
- src/containers/Settings/Settings.js
- src/features/WalletDataSlice.js
- src/wallet/activity_log.ts
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
> Fix/various issues - 918, 915, 902, 905, 910

- src/components/ConfirmPopup/index.js
- src/components/coins/coins.js
- src/components/index.js
- src/components/panelConnectivity/panelConnectivity.js
- src/containers/Send/Send.js
- src/containers/Withdraw/Withdraw.js
Issue #920: Confirm Popup appears to confirm Send and Withdrawal
Other fixes:
Issue #925: text change: 'Statecoin created in wallet' to 'Original'
Host URL truncated links corrected
> #920, #925 : Confirm Popup for Send and Withdraw

- package.json
> feat/ add dev-windows as a script for windows users

- src/components/swaps/CountdownTimer/CountdownTimer.js
- src/components/swaps/swaps.css
- src/containers/Send/Send.css
- src/containers/Send/Send.js
- src/containers/Withdraw/Withdraw.css
Issue #935 : Grey action buttons now blue
Swap Timer reset to 6 mins from 1 hour for GUI improvement
> Issue #935 Action Button Blue + Swap Timer Adjustment

- src/wallet/wallet.ts
If tx with same amount but different tx id is found in mempool, then re-do deposit confirm.
> handle replaced tx in mempool

- src/components/coins/coins.js
- src/containers/Swap/Swap.js
- src/electron-starter.js
- src/features/WalletDataSlice.js
- src/settings.json
- src/wallet/swap/swap.ts
- src/wallet/wallet.ts
Includes: 
- Enhancement/529 recover at transfer finalize
-  Earlier coin spent status update (pull request #955)
> Simplifying autoswap logic

- src/wallet/swap/swap.ts
Keep waiting in phase "init" or phase 0 indefinitely.
> Keep coins in swap if waiting in swap pool.

- src/components/QRCodeGenerator/QRCodeGenerator.js
- src/components/coins/coins.js
- src/containers/Withdraw/Withdraw.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
Issue #960 Fixed
QR code has correct value
> Fix/960 QRcode Nan Value 917 Mininum withdrawal size

- src/containers/Receive/Receive.css
> CHORE: Issue #978 Receive Index Button 5 Digits

- src/wallet/recovery.ts
- src/wallet/util.ts
Issue #849: Testnet addresses now have prefix 'tc' and mainnet prefix 'sc'
> FEAT: Testnet format statecoin addresses

- src/components/activity/activity.js
- src/containers/Receive/Receive.js
- src/features/WalletDataSlice.js
- src/wallet/swap/swap.ts
- src/wallet/wallet.ts
Issue #997 : Swaps no longer record twice in activity log
Issue #889 : Receive activity now listed
> Issues: #997 #889 Repeated Swaps and Receive Activity

- src/wallet/statecoin.ts
- src/wallet/swap/swap.ts
- src/wallet/wallet.ts
No two coins should have the same shared_key_id
> Prevent new replica coins

- src/components/coins/coins.js
> Dont show withdrawing coins

- src/components/coins/SwapStatus/SwapStatus.js
- src/components/coins/coins.js
- src/wallet/statecoin.ts
- src/wallet/swap/swap.ts
Issue #1008 
New swap phase arrangement:
8 Swap Phases
> Issue #1008 Expand Swap Phases

- src/components/ConfirmPopup/index.js
- src/containers/Deposit/Deposit.js
On deposit screen and withdrawal confirm box
> Withdrawal fee notices

- package.json
- src/components/panelConnectivity/panelConnectivity.js
- src/containers/App/App.js
- src/containers/Home/Home.js
- src/wallet/mercury/info_api.ts
- src/wallet/swap/swap.ts
- src/wallet/types.ts
Alert displayed if wallet version not supported by server. 
General alert displayed set by server. 
Registering for swap prevented for unsupported wallet version (and alert displayed).
> Version check features

- src/components/header/TorInfo/TorCircuit.jsx
- src/wallet/mercury/torcircuit_api.ts
- src/wallet/wallet.ts
- tor-adapter/server/index.js
> Tor info update logic

- src/containers/Swap/Swap.js
- src/wallet/wallet.ts
> Issue #1043 Auto Swap After Rejoin

- package.json
- src/containers/CreateWalletInfo/CreateWalletInfo.js
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/wallet/mocks/mock_http_client.ts
- src/wallet/test/swap.test.js
- src/wallet/test/test-utils.js
- src/wallet/wallet.ts
Reapply merge of pull request #1072 to develop branch
> Undo revert merge of pull request #1072

- src/wallet/statecoin.ts
- src/wallet/swap/swap.phase0.ts
- src/wallet/swap/swap.phase1.ts
- src/wallet/swap/swap.phase2.ts
- src/wallet/swap/swap.phase3.ts
- src/wallet/swap/swap.phase4.ts
- src/wallet/swap/swap.ts
- src/wallet/test/swap.phase0.test.js
- src/wallet/test/swap.phase2.test.js
- src/wallet/test/swap.phase4.test.js
- src/wallet/test/swap.test.js
moves swaps into separate files
> add base for refactoring swaps

- src/components/panelConnectivity/panelConnectivity.js
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
Issue #1117 fixed:
• Error messaging changed and more accurate
• No error shown joining auto-swap mid-swap
> Error message fix and join auto-swap error fix

- src/components/coins/coins.js
- src/components/transactionsBTC/transactionsBTC.js
- src/wallet/mercury/deposit.ts
- src/wallet/mercury/withdraw.ts
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
Don't update status until deposit is finalized. 
User info and tootips for deposit tx.
> Deposit logic

- src/components/coins/Coin/Coin.js
- src/components/coins/SwapStatus/SwapStatus.js
- src/wallet/statecoin.ts
- src/wallet/swap/swap.ts
- src/wallet/swap/swap_utils.ts
- src/wallet/test/components.test.js
- src/wallet/test/swap.phase4.test.js
#1154 : indication of coin punishment and timeouts
> swap error messaging

- src/components/coins/CoinsList.js
- src/components/header/TorInfo/TorCircuit.jsx
- src/components/header/TorInfo/TorCircuitNode.jsx
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
Issue #1179 
Collating intervals for more efficient Web API
> #1179 More Efficient Intervals

- src/components/coins/Coin/Coin.js
> Fix/#1171 and #1163

- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
Fixes issue #1225 Autoswap un checked coin stays in queue
#1226 No coin in swap pool, but coin goes straight to "in queue"
#1227 Coins no in pool, but when taken out on AutoSwap it displays error message. 
#1228 Can't get any coins to join pool
> Remove in swap value when unchecking autoswap mode.

- public/electron.js
- src/electron-starter.js
> Fix/1237, Fix/1152, Fix/1236 - Windows issues

- src/components/WarningPopup/index.js
- src/components/coins/CoinsList.js
- src/containers/BackupTx/BackupTx.js
- src/containers/Receive/Receive.js
- src/features/WalletDataSlice.js
- src/wallet/mercury/transfer.ts
- src/wallet/recovery.ts
- src/wallet/swap/swap.ts
- src/wallet/test/mercury.test.js
- src/wallet/test/mock_swap.test.js
- src/wallet/test/swap.complete.test.js
- src/wallet/test/swap.init.test.js
- src/wallet/test/swap.phase0.test.js
- src/wallet/test/swap.phase1.test.js
- src/wallet/test/swap.phase2.test.js
- src/wallet/test/swap.phase3.test.js
- src/wallet/test/swap.phase4.test.js
- src/wallet/test/swap_main.test.js
- src/wallet/test/util.test.js
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
Reverts layer2tech/mercury-wallet#1267
> Revert "Fix/1254 get bip32 for btc address error"

- src/components/coins/Coin/Coin.js
- src/components/coins/coins.css
- src/settings.json
- src/wallet/config.ts
- src/wallet/wallet.ts
Only specified coin amounts able to join swap groups.
> Permitted swaps

- src/components/transactionsBTC/transactionsBTC.js
- src/containers/Deposit/Deposit.css
> Fix/1211 deposit delay, Fix/1256 order of deposit

- package.json
- src/components/coins/CoinsList.js
- src/components/transactionsBTC/transactionsBTC.js
- src/containers/Deposit/Deposit.css
- src/containers/LoadWallet/LoadWallet.js
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/wallet/config.ts
- src/wallet/swap/swap.ts
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
This reverts commit c2fef777459dbbd3b3877c5bf99c1b61bf656e54.
> Revert "release: v0.6.9 (#1287)"

- src/components/transactionsBTC/transactionsBTC.js
> hotfix/deposit UI update

- src/containers/RestoreWallet/RestoreWallet.js
- src/containers/Withdraw/Withdraw.js
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
Issue #1061 
Improve backup file checks.
> Backup file errors

- src/components/coins/CoinsList.js
- src/wallet/swap/info_api.ts
- src/wallet/test/test_data.js
- src/wallet/wallet.ts
Fixes issue #1312 Auto swap not working
> Do not change coins list order of coins in a swap or awaiting swap

- src/wallet/wallet.ts
Issue #1304: Wallet Crashes when no Server Connection
> Issue #1304: Wallet Crashes when no Server Connection

- package.json
- src/components/activity/activity.js
- src/index.js
- src/wallet/activity_log.ts
- src/wallet/test/wallet.test.js
Suppress a warning about TransactionBuilder deprication.
Fixes issue #1335 - Deprecated error
> Suppress warning

- README.md
- main.js
- package.json
- public/electron.js
- src/electron-starter.js
- src/features/WalletDataSlice.js
- src/settings.json
- src/wallet/config.ts
- tor-adapter/package.json
- tor-adapter/server/config.js
- Upgrade electron to version 13.6.9
- Correct paths for development mode
- Remove unused code
- Add instructions for running with devtools enabled
> Electron v13 6 9

- src/containers/Settings/Settings.css
> Issue #1334 Tor Proxy Dark Mode Fix

- src/containers/App/AppDarkMode.css
> chore: fix dark mode send recv buttons

- src/components/header/TorInfo/torCircuit.css
- src/components/index.css
> Issue #1374: Tor Circuit CSS affecting all li elements

- src/components/coins/Coin/Coin.js
- src/containers/Deposit/Deposit.js
> fix/1383 fix/1382

- src/wallet/recovery.ts
- src/wallet/wallet.ts
Enable recovery of generated addresses
Verify deposits
> Recover keygen

- src/components/coins/Coin/Coin.js
- src/containers/Settings/Settings.js
- src/wallet/wallet.ts
Tooltips on coin and settings button
Checks and error messages to prevent user from sending/swapping original statecoin
> Duplicate deposit improvements

- src/wallet/wallet.ts
The duplicate check function fixes coins with incorrect txid:vout from old wallet deposit tx replacement.
> Recovery of RBF error coin

- src/components/coins/CoinsList.js
Fix days to expiry bug if 30-60 days remaining
> Days to expiry

- src/components/coins/CoinsList.js
> Copy Withdrawal TX to clipboard

- src/components/Loading/Loading.css
- src/components/Loading/Loading.js
- src/components/ProgressBar/ProgressBar.css
- src/components/ProgressBar/ProgressBar.js
- src/features/WalletDataSlice.js
> #1470 #1469 recovery freeze ui fix

- src/components/BackupWalletPopup/index.js
- src/components/ConfirmPopup/index.js
- src/components/ErrorPopup/index.js
- src/components/WarningPopup/index.js
- src/components/coins/CoinsList.js
- src/components/createStatecoin/valueSelection/valueSelection.js
- src/components/header/TorInfo/TorCircuit.jsx
- src/components/index.css
- src/containers/Receive/Receive.css
- src/containers/Settings/Settings.js
> CHORE: #1445: Clearer UI Buttons

- src/components/coins/Coin/Coin.js
- src/components/coins/CoinsList.js
- src/components/coins/coins.css
- src/containers/App/App.css
- src/features/WalletDataSlice.js
- src/wallet/activity_log.ts
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
> Hotfix/1494 clearer expiry UI

- package.json
- src/containers/Swap/Swap.js
- src/features/WalletDataSlice.js
- src/store.ts
- src/wallet/wallet.ts
Resolves memory leak and UI responsiveness issues.
> Remove rate limiter

- src/containers/LoadWallet/LoadWallet.js
> Distinguish "E" character from "Enter" kerypress in password entry box.

- src/containers/BackupTx/BackupTx.css
- src/containers/BackupTx/BackupTx.js
Issue #1553 
- Tooltips added to Backup Tx Status
> FEAT: Tooltips for Backup Tx Status

- src/containers/BackupTx/BackupTx.js
Issue #1554 - CPFP Confirmation Notification
> FEAT: CPFP Confirmation Notification

- package.json
- src/wallet/mercury/transfer.ts
- src/wallet/mocks/mock_http_client.ts
- src/wallet/test/mercury.test.js
Reverts layer2tech/mercury-wallet#1563
> Revert "Update mercury.test.js"

- src/features/WalletDataSlice.js
- src/wallet/mocks/mock_http_client.ts
- src/wallet/swap/swap.init.ts
- src/wallet/swap/swap.phase0.ts
- src/wallet/swap/swap.phase1.ts
- src/wallet/swap/swap.phase2.ts
- src/wallet/swap/swap.phase3.ts
- src/wallet/swap/swap.phase4.ts
- src/wallet/test/swap_main.test.js
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
Issue #1514:
- Resume swap will run if wallet loaded with coins that have completed swap
- Swap data correctly deleted if coin not in swap phase 4
- double swap semaphore use removed
> FIX Issue #1514: Statechain Not Found Error

- src/containers/App/App.js
- src/containers/RestoreWallet/RestoreWallet.js
- src/features/WalletDataSlice.js
- src/wallet/electrs.ts
- src/wallet/recovery.ts
- src/wallet/test/recovery.test.js
Issue #1575:
• Retry recovery if network failure
• Correct error message shows rather than just "Network Error"
• If recovery on a specific coin fails for a protocol issue, the recovery will still go ahead
• Testing for new features
> Issue #1575: Recovery Error Handling

- src/features/WalletDataSlice.js
- src/wallet/test/mock_swap.test.js
- src/wallet/test/statecoin.test.js
- src/wallet/test/wallet.test.js
- src/wallet/wallet.ts
Fixes issue #1662 Coins disappeared from wallet.
> Save statecoin after swap

- src/wallet/electrum.ts
- tor-adapter/server/electrum.js
Issue #1676 
Issue with display of error messages inside dialog boxes in wallet.
> Move long error messages from dialog box to console

- src/application/webStore.js
- src/features/WalletInfoSlice.js
- src/store.ts
- src/wallet/test/webStore.test.js
- src/wallet/wallet.ts
Issue https://github.com/layer2tech/mercury-wallet/issues/1649
- Add test for setter and getter functions of webStore
- Add test for operations on wallet using webStore
> Test / WebStore

- package.json
- src/components/header/TorInfo/TorCircuit.jsx
- src/components/header/header.js
- src/containers/App/App.js
- src/containers/Settings/Settings.js
- src/features/WalletDataSlice.js
- src/wallet/wallet.ts
> Issue #1737: SettingsPage Tor & I2P

- src/containers/Send/Send.js
- src/features/WalletDataSlice.js
> fix: implement error message on no coin selected while sending coin

- src/components/coins/CoinFunctionUtils/CoinFunctionUtils.js
- src/components/coins/CoinsList.js
- src/components/panelConnectivity/panelConnectivity.js
- src/features/WalletDataSlice.js
Issue #1840 Fixed:
• Expiry data refreshes quicker
• Shows loading expiry instead of incorrect expiry data on wallet load
> FIX: Issue #1840 Time Until Expiry

- tor-adapter/server/index.js
#1852 - if i2pd or tor goes down, server automatically restarts the thread
> Issue #1852: I2Pd Restart

- src/components/header/header.js
- src/components/panelConnectivity/panelConnectivity.js
> feat: display warning if i2pd doesn't start

- src/components/InfoModal/InfoModal.js
> fix: add copied button to txid for coin

- src/components/coins/Coin/Coin.js
- src/wallet/recovery.ts
- src/wallet/statecoin.ts
- src/wallet/wallet.ts
Recovery fix
Min fee not met backup status
enable withdrawal if backup error
> withdraw expired

- src/components/AutoSwapToggle/AutoSwapToggle.js
- src/components/coins/Coin/Coin.js
- src/components/coins/CoinFunctionUtils/CoinFunctionUtils.js
- src/components/coins/CoinsList.js
- src/components/coins/coins.css
- src/components/panelCoinsActivity/panelCoinsActivity.js
> feat: swap from main coinlist

- src/containers/Settings/Settings.css
- src/containers/Settings/Settings.js
- src/features/WalletDataSlice.js
- src/wallet/mercury/transfer.ts
- src/wallet/swap/swap.phase4.ts
- src/wallet/swap/swap.ts
- src/wallet/test/mercury.test.js
- src/wallet/test/swap.phase4.test.js
- src/wallet/wallet.ts
> feat: text box for adding txids to exclude
